name: "Push: main"

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    uses: ./.github/workflows/call-build.yml
    with:
      tag: ${{ github.sha }}
    secrets: inherit
  deploy:
    uses: ./.github/workflows/call-update_version.yml
    with:
      version: ${{ github.sha }}
    secrets: inherit
    needs: [build]
